print("Welcome to the SUPER Name-Generator", end="")
input()
miasto = input("What is the name of the city where you were born? ")
zwierze = input("What is the name of your pet? ")
print("The name of your band is: " + miasto + zwierze)
